Fix compilation issues by using the latest commit in synthrs
Involves an apparent API change where output path is changed to a
write-able File object.

Besides changing the synthrs git reference, the other Cargo changes are
made by the cargo tooling.

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/user/.cargo/git/checkouts/synthrs-a4b8c03c849616c3/9e9724c/src/lib.rs:1:1
  |
1 | #![feature(fn_traits, unboxed_closures)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/user/.cargo/git/checkouts/synthrs-a4b8c03c849616c3/9e9724c/src/lib.rs:1:12
  |
1 | #![feature(fn_traits, unboxed_closures)]
  |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `synthrs` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```